In [6]:
# Importing Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
# Loading Models

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [8]:
# Loading data

from sklearn.datasets import load_digits
digits = load_digits()

In [9]:
# Details of the dataset

dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [10]:
# Splitting the data into Train and Test Datasets

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [13]:
# Logistic Regression

lr = LogisticRegression(max_iter = 10000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9611111111111111

In [14]:
# Support Vector Machines

svc = SVC()
svc.fit(X_train, y_train)
svc.score(X_test, y_test)

0.9814814814814815

In [15]:
# Random Forest

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [21]:
# Creating a Function

def diff_model(models, X_train, y_train, X_test, y_test):
    models.fit(X_train, y_train)
    model_score = models.score(X_test, y_test)
    return model_score

In [38]:
diff_model(LogisticRegression(max_iter = 10000), X_train, y_train, X_test, y_test)

0.9232053422370617

In [24]:
diff_model(SVC(), X_train, y_train, X_test, y_test)

0.9814814814814815

In [25]:
diff_model(RandomForestClassifier(), X_train, y_train, X_test, y_test)

0.9722222222222222

# K-Fold Validation

### Basic Example

In [26]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [27]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


## Using K-Fold Validation for our Example

In [39]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

score_l = []
score_svc = []
score_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    
    score_l.append(diff_model(LogisticRegression(max_iter = 10000), X_train, y_train, X_test, y_test))
    score_svc.append(diff_model(SVC(), X_train, y_train, X_test, y_test))
    score_rf.append(diff_model(RandomForestClassifier(n_estimators=40), X_train, y_train, X_test, y_test)) 

In [35]:
score_l

[0.9248747913188647, 0.9398998330550918, 0.9232053422370617]

In [36]:
score_svc

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [40]:
score_rf

[0.9315525876460768, 0.9449081803005008, 0.9181969949916527]

# Cross Validation  - cross_val_score

In [47]:
from sklearn.model_selection import cross_val_score

In [49]:
cross_val_score(LogisticRegression(max_iter = 10000), digits.data, digits.target,cv=3)

array([0.92487479, 0.93989983, 0.92320534])

In [50]:
cross_val_score(SVC(), digits.data, digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [55]:
cross_val_score(RandomForestClassifier(n_estimators=100), digits.data, digits.target,cv=3)

array([0.93656093, 0.96160267, 0.92320534])

# Exercise

In [70]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
from sklearn.datasets import load_iris

In [57]:
iris = load_iris()

In [58]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [59]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target)

In [72]:
def models_iris(model,X_train, y_train, X_test,  y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [74]:
models_iris(LogisticRegression(), X_train, y_train, X_test, y_test)

1.0

In [76]:
models_iris(SVC(), X_train, y_train, X_test, y_test)

1.0

In [77]:
models_iris(RandomForestClassifier(), X_train, y_train,X_test, y_test)

0.9736842105263158

In [78]:
models_iris(DecisionTreeClassifier(), X_train,  y_train, X_test,y_test)

0.9473684210526315

# K-Fold Validation

In [79]:
k_fold = StratifiedKFold(n_splits=3)
k_fold

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [82]:
model_lr = []
model_dt = []
model_svc = []
model_rf =[]

for train_index, test_index in k_fold.split(iris.data, iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], iris.target[train_index], iris.target[test_index]
    model_lr.append(models_iris(LogisticRegression(max_iter = 10000), X_train, y_train, X_test, y_test))
    model_svc.append(models_iris(SVC(), X_train, y_train, X_test, y_test))
    model_rf.append(models_iris(RandomForestClassifier(), X_train, y_train,X_test, y_test))
    model_dt.append(models_iris(DecisionTreeClassifier(), X_train,  y_train, X_test,y_test))

In [84]:
print(model_lr)

[0.98, 0.96, 0.98]


In [85]:
model_dt

[0.98, 0.94, 0.98]

In [86]:
model_rf

[0.98, 0.94, 0.96]

In [87]:
model_svc

[0.96, 0.98, 0.94]

# Cross_val_score

In [108]:
lr_score = cross_val_score(LogisticRegression(max_iter=10000), iris.data, iris.target, cv=3)
lr_score

array([0.98, 0.96, 0.98])

In [109]:
svc_score = cross_val_score(SVC(), iris.data, iris.target, cv=3)
svc_score

array([0.96, 0.98, 0.94])

In [110]:
rf_score = cross_val_score(RandomForestClassifier(n_estimators=50), iris.data, iris.target, cv=3)
rf_score

array([0.98, 0.94, 0.98])

In [111]:
dt_score = cross_val_score(DecisionTreeClassifier(max_depth=10), iris.data, iris.target, cv=3)
dt_score

array([0.98, 0.94, 0.96])

In [113]:
np.average(lr_score), np.average(svc_score), np.average(dt_score), np.average(rf_score)

(0.9733333333333333, 0.96, 0.96, 0.9666666666666667)

# Logistic Regression is giving the best average score.